### ISSUE TITLE
DOMXPath::query(): Undefined namespace prefix

### ISSUE THREAD

**Issue by peter279k** [PHPOffice/Common#20]
Test branch: ```develop```.
Please consider the following error output:

```
PhpOffice\Common\Tests\XMLReaderTest::testShouldThrowExceptionIfNamespaceIsNotKnown
DOMXPath::query(): Undefined namespace prefix
```

And it seems that this test will be broken when executing the ```$this->xpath->query($path);```.
Please see more details about this [Travis build log](https://travis-ci.org/peter279k/Common/jobs/350227627).

Thanks.

**Comment by troosan** [comment]
That's strange, the test indeed checks that an exception is thrown.

**Comment by troosan** [comment]
expecting the following works, at least for php 7.2.
```php
    /**
     * @expectedException PHPUnit_Framework_Error
     */
```
I'm not sure about other versions though

**Comment by ch-dani** [comment]
i don't know why i am facing the same issue. DOMXPath::query(): Undefined namespace prefix when i try to change .docx file to pdf file

Please help my guys.

**Comment by ch-dani** [comment]
is there any solution to this problem. Actually problems comes when there is any image in .docs file.
